import type { Opportunity } from './types'

// Seed opportunities · portado del standalone (3 opps: JPMorgan / NYC DOH / St. Jude).
export const SEED_OPPS: Opportunity[] = [
    {
        id: 'OPP-1001',
        name: 'JPMorgan — Atlanta HQ',
        company: 'JPMorgan',
        vertical: 'Financial',
        stage: 'Opportunity',
        probability: 60,
        closeDate: '2026-08-15',
        color: 'orange',
        primaryMfr: 'Steelcase',
        ancillaryMfrs: ['Coalesse', 'Designtex'],
        revenue: { furniture: 600000, arch: 150000, install: 85000, prof: 25000 },
        participants: [
            { name: 'Gensler ATL', role: 'A&D Firm' },
            { name: 'Turner Construction', role: 'General Contractor' },
        ],
        gsaContract: '',
        contractVehicle: '',
        pricingTier: '',
        gpo: '',
        phasedSchedule: '',
        generalContractor: 'Turner Construction',
        permitStatus: '',
        prevailingWage: false,
        headcount: '',
        budgetSF: '',
        sources: [],
        aiGenerated: false,
    },
    {
        id: 'OPP-1002',
        name: 'NYC Dept. of Health — Brooklyn',
        company: 'NYC DOH',
        vertical: 'Government',
        stage: 'Quote',
        probability: 80,
        closeDate: '2026-07-30',
        color: 'green',
        primaryMfr: 'Herman Miller',
        ancillaryMfrs: [],
        revenue: { furniture: 120000, arch: 0, install: 18200, prof: 10000 },
        participants: [{ name: 'City Planning Dept', role: 'End User (Client)' }],
        gsaContract: 'GS-27F-00000',
        contractVehicle: 'GSA',
        pricingTier: '',
        gpo: '',
        phasedSchedule: '',
        generalContractor: '',
        permitStatus: '',
        prevailingWage: false,
        headcount: '',
        budgetSF: '',
        sources: [],
        aiGenerated: false,
    },
    {
        id: 'OPP-1003',
        name: 'St. Jude Expansion',
        company: 'St. Jude',
        vertical: 'Healthcare',
        stage: 'Lead',
        probability: 30,
        closeDate: '2026-11-01',
        color: 'red',
        primaryMfr: 'Haworth',
        ancillaryMfrs: ['Carolina'],
        revenue: { furniture: 250000, arch: 50000, install: 40000, prof: 15000 },
        participants: [],
        gsaContract: '',
        contractVehicle: '',
        pricingTier: '',
        gpo: '',
        phasedSchedule: '',
        generalContractor: '',
        permitStatus: '',
        prevailingWage: false,
        headcount: '',
        budgetSF: '',
        sources: [],
        aiGenerated: false,
    },
]
